
export const GET_MY_ASSETS_URL = "/bgrgb/v1/user_balances/get_all_user_balance"
export const POST_USER_REGISTER = "/bgrgb/v1/users/action/register"
export const GET_BTC_PRICE = "/bgrgb/v1/assets/action/get_btc_price"
export const POST_DEPOSIT_URL = "/bgrgb/v1/transaction/action/deposit"
export const POST_WITHDRAW_URL = "/bgrgb/v1/transaction/action/withdraw"
export const GET_INVOICE_AMOUNT_URL = "/bgrgb/v1/transaction/action/getInvoiceAmount"
export const GET_MINT_WHITELIST_URL = "/bgrgb/v1/mint_white_list/action/get_by_publicKey"
export const GET_MINT_INFO_BY_ROUND_URL = "/bgrgb/v1/mint_configs/action/get_by_round"
export const POST_MINT_URL = "/bgrgb/v1/mint_white_list/action/mint"
export const GET_ROUND2_MINTED = "/bgrgb/v1/mint_white_list/action/getRound2Events"
export const GET_MINT_ROUND_INFO = "/bgrgb/v1/mint_white_list/action/getMintInfo"
export const POST_TRANSFER_ASSETS = "/bgrgb/v1/user_balances/transfer"
export const GET_EVENT_URL = "/bgrgb/v1/events/action/list"